apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: react-demoapp
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: react-demoapp
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: react-demoapp
    spec:
      containers:
      - name: react-demoapp
        # Run this image
        image: dockernaru99/react-webapp:04